steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/spots-api', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/spots-api']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'spots-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/spots-api'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--add-cloudsql-instances'
      - 'spots-app-493222:us-central1:spots-app'
      - '--set-env-vars'
      - 'DATABASE_URL=postgresql://admin:Spots2026@/spots-database?host=/cloudsql/spots-app-493222:us-central1:spots-app'

images:
  - 'gcr.io/$PROJECT_ID/spots-api'
